@startuml Structure

' Copy this into https://www.plantuml.com/plantuml/uml/
' and save the url in the README file before committing changes

title Dependency Tree

folder internal {
  file server_go {
  }


  folder app {
  }
  folder controllers {
  }
  folder models {
  }
  folder services {
  }
  folder views {
  }
}

folder pkg {
  folder imgbb {
  }
  folder tsp {
  }
}

folder cmd {
}

cmd <<-- server_go
cmd <<-- app

server_go <<-- app
server_go <<-- controllers

controllers <<-- models
controllers <<-- services
controllers <<-- views
controllers <<-- tsp
controllers <<-- imgbb
controllers <<-- app

services <<-- models

app <<-- models

@enduml